name: vrouter-synchronizer
accessor:
  username: xosadmin@opencord.org
  password: "@/opt/xos/services/vrouter/credentials/xosadmin@opencord.org"
dependency_graph: "/opt/xos/synchronizers/vrouter/model-deps"
steps_dir: "/opt/xos/synchronizers/vrouter/steps"
sys_dir: "/opt/xos/synchronizers/vrouter/sys"